// <auto-generated />
namespace DekanatFPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PlanWithGroup_in_Student : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PlanWithGroup_in_Student));
        
        string IMigrationMetadata.Id
        {
            get { return "202108101059422_PlanWithGroup_in_Student"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
