// <auto-generated />
namespace DekanatFPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class YearsIndividualPlans_in_Group_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(YearsIndividualPlans_in_Group_2));
        
        string IMigrationMetadata.Id
        {
            get { return "202108101013101_YearsIndividualPlans_in_Group_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
