// <auto-generated />
namespace DekanatFPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Name_for_Group : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Name_for_Group));
        
        string IMigrationMetadata.Id
        {
            get { return "202108100641319_Name_for_Group"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
