// <auto-generated />
namespace DekanatFPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StartYear_in_Group : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StartYear_in_Group));
        
        string IMigrationMetadata.Id
        {
            get { return "202108100813035_StartYear_in_Group"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
