// <auto-generated />
namespace DekanatFPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ShortName_in_Specialization : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ShortName_in_Specialization));
        
        string IMigrationMetadata.Id
        {
            get { return "202108100758235_ShortName_in_Specialization"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
